### PR TITLE
Added settings for stdlib

### PR DESCRIPTION
**Pull request by peastman**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

### CODE REVIEW

**Comment by peastman** [comment]
@conda-forge-admin, please rerender

**Comment by peastman** [comment]
All tests passed.  Does this look ok to everyone?

**Review by mikemhenry — APPROVED** [review]
LGTM!

**Comment by mikemhenry** [comment]
I double-checked that we are targeting the correct channel + the stdlib fixes look correct, I am going to dobule check the output of a few CI logs but if that looks good I will get this merged and keep an eye on it to make sure the build kicks off and runs okay post merge

**Comment by peastman** [comment]
Thank you, that's great.

**Comment by mattwthompson** [comment]
Thanks!

**Pull request merged**
