### PR TITLE
Build 8.1.1 release candidate

### PR DESCRIPTION
**Pull request by peastman**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

### CODE REVIEW

**Comment by peastman** [comment]
@conda-forge-admin, please rerender

**Comment by peastman** [comment]
All the windows builds are failing with this error:

```
Error while loading conda entry point: conda-libmamba-solver (DLL load failed while importing bindings: The specified procedure could not be found.)
Traceback (most recent call last):
  File "C:\Miniforge\Scripts\conda-mambabuild-script.py", line 5, in <module>
    from boa.cli.mambabuild import main
  File "C:\Miniforge\lib\site-packages\boa\cli\mambabuild.py", line 21, in <module>
    from boa.core.solver import MambaSolver
  File "C:\Miniforge\lib\site-packages\boa\core\solver.py", line 22, in <module>
    import libmambapy
  File "C:\Miniforge\lib\site-packages\libmambapy\__init__.py", line 7, in <module>
    raise e
  File "C:\Miniforge\lib\site-packages\libmambapy\__init__.py", line 4, in <module>
    from libmambapy.bindings import *  # noqa: F401,F403
ImportError: DLL load failed while importing bindings: The specified procedure could not be found.
```

What does that mean?

**Comment by jakirkham** [comment]
Let's try running. There have been a number of fixes made in the past day

@conda-forge-admin , please restart CI

**Comment by peastman** [comment]
This time there was only one failure.  Here's the error:

> 2024-01-04T00:12:19.2391171Z %SRC_DIR%\build\plugins\amoeba\wrappers\AmoebaOpenMMCWrapper.cpp(12): fatal error C1075: '{': no matching token found

That file gets generated programmatically during the build.  It passed on all the other builds, including the other Windows builds, so I suspect something went wrong during generating the file that caused it to be truncated.  I'll try rerunning it to see if it was a transient problem.

**Comment by peastman** [comment]
That worked.  Who knows?  Except I realized I targeted the wrong branch.  It should be merging into rc, not main.  I'll close this and open a new PR.

**Comment by jakirkham** [comment]
Glad to hear it Peter 😄

FWIW it is possible to [change the base branch for a PR]( https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request )

Depending on how cleanly the changes apply, that may be more or less work

**Pull request closed without merging**
