### PR TITLE
Build 7.5.1

### PR DESCRIPTION
**Pull request by peastman**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by peastman** [comment]
@conda-forge-admin, please rerender

**Comment by jaimergp** [comment]
Looks good! The Windows tests fail because of an error in `test_openmm.bat`. The fix is [here](https://github.com/conda-forge/openmm-feedstock/pull/53/commits/49c2168b9aec314f36cfbbd1d6fdd06bf4a9234b). I don't know why this stopped working (it used to work for 7.5.0), but anyway, apply that change and it should be all green!

**Comment by jaimergp** [comment]
LGTM!

**Comment by peastman** [comment]
Thanks!

**Comment by peastman** [comment]
It appears that only the ARM builds have been generated.  I can't find any record of the Azure builds ever even running.  Is there something else I need to do?

**Comment by jaimergp** [comment]
Looks like Azure wasn't triggered, right. In these cases an empty commit to master works:

```
git commit --allow-empty -m "Retrigger CI"
git push upstream master
```

**Comment by peastman** [comment]
Thanks!  It looks like all packages are up, so I'll post the announcement.

Do you know if that trick is documented somewhere?

**Comment by jaimergp** [comment]
I'll open a PR to cover it in our docs!

**Pull request merged**
