### PR TITLE
dev build of openmm

### PR DESCRIPTION
**Pull request by mikemhenry**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mikemhenry** [comment]
@conda-forge-admin, please rerender

**Comment by peastman** [comment]
What's the goal of this PR?  Is this just for debugging?

**Comment by mikemhenry** [comment]
@peastman Few goals:

1) debugging why our last release had the segfaults/testing future releases
2) Making it easier for people to install the dev/HEAD version of openmm

Right now a lot of the work in the openmm-ml spacing is happening faster than openmm releases are and by allowing users to install openmm with the `dev` label, they can install a version of openmm that has the latest PRs merged in + in binary compatible with conda-forge, see this comment/thread on slack https://openmm.slack.com/archives/GMNUN3ZV2/p1650568039713289

**Comment by peastman** [comment]
Got it.  Let's update the documentation at https://github.com/openmm/openmm/blob/master/devtools/CONDA_FORGE_RELEASES.md to add a section on dev builds.  Based on what you've done here, it looks like the plan is

- They will be built from the `dev` branch of this repository.
- They will be posted with the `openmm_dev` label.
- They won't be built on any automated schedule.  We'll trigger a new dev build by hand whenever we decide it would be a good idea.

Does that all match what you had in mind?

**Comment by mikemhenry** [comment]
@peastman yes, exactly! I will make a PR to update that document adding steps/checklist for the dev build. Right now I'm just working on getting things to pass the CI, but then I will get everything documented.

**Comment by peastman** [comment]
Ok, sounds good to me.  Your changes look right as far as I can tell.  I'm not sure what's causing all the build failures.

**Comment by jaimergp** [comment]
New dependency needed?

```
/home/conda/feedstock_root/build_artifacts/openmm_1650923055449/work/libraries/asmjit/asmjit/core/cpuinfo.cpp:18:12: fatal error: sys/auxv.h: No such file or directory
```

This is part of glibc so no clue. Is this only available in a more recent version than 2.17?

**Comment by mikemhenry** [comment]
Love when I stumble into issues with familiar faces :) https://github.com/conda-forge/conda-forge.github.io/issues/1625
Going to see if that fixes it.

**Comment by mikemhenry** [comment]
That might fix the linux builds, but this is why the osx builds are failing:

```
2022-04-25T21:50:51.1346250Z /Users/runner/miniforge3/conda-bld/openmm_1650923045777/work/libraries/asmjit/asmjit/core/../core/environment.h:104:29: error: 'TARGET_OS_OSX' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_OSX]
2022-04-25T21:50:51.1415270Z #elif defined(__APPLE__) && TARGET_OS_OSX
2022-04-25T21:50:51.1515830Z                             ^
2022-04-25T21:50:51.1621630Z OpenMMSwigHeaders.i:1619: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
2022-04-25T21:50:51.1722150Z OpenMMSwigHeaders.i:1753: Warning 453: Can't apply (std::vector< Vec3,std::allocator< Vec3 > > &OUTPUT). No typemaps are defined.
2022-04-25T21:50:51.1819590Z OpenMMSwigHeaders.i:1756: Warning 453: Can't apply (std::vector< Vec3,std::allocator< Vec3 > > &OUTPUT). No typemaps are defined.
2022-04-25T21:50:51.1922770Z OpenMMSwigHeaders.i:1759: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
2022-04-25T21:50:51.2024610Z OpenMMSwigHeaders.i:1864: Warning 453: Can't apply (OpenMM::Context &OUTPUT). No typemaps are defined.
2022-04-25T21:50:51.3358690Z OpenMMSwigHeaders.i:1945: Warning 453: Can't apply (std::vector< Vec3,std::allocator< Vec3 > > &OUTPUT). No typemaps are defined.
2022-04-25T21:50:51.3517170Z OpenMMSwigHeaders.i:1948: Warning 453: Can't apply (std::vector< Vec3,std::allocator< Vec3 > > &OUTPUT). No typemaps are defined.
2022-04-25T21:50:51.4590050Z 1 error generated.
2022-04-25T21:50:51.4604510Z make[2]: *** [CMakeFiles/OpenMM.dir/build.make:188: CMakeFiles/OpenMM.dir/openmmapi/src/CompiledExpressionSet.cpp.o] Error 1
2022-04-25T21:50:51.4606620Z make[1]: *** [CMakeFiles/Makefile2:589: CMakeFiles/OpenMM.dir/all] Error 2
2022-04-25T21:50:51.4608040Z make[1]: *** Waiting for unfinished jobs....
2022-04-25T21:50:51.5611970Z ./swig_lib/python/extend.i:414: Warning 509: Ov
```

**Comment by mikemhenry** [comment]
@jaimergp any ideas why its trying to pull in [mesa-libgl-devel-cos6-x86_64](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=498964&view=logs&j=3b077b59-19b3-5c3c-d9ea-4f2d359714ca&t=4427250c-9566-5227-2be0-fd328c273206&l=34) instead of cos7? I thought the cdt macro would adjust to cos7

**Comment by mikemhenry** [comment]
@conda-forge-admin, please rerender

**Comment by mikemhenry** [comment]
Sorry for the ping Jaime, it did just need a re-rendering

**Comment by mikemhenry** [comment]
@peastman I see that this [PR](https://github.com/openmm/openmm/pull/3517) introduced this

```
2022-04-28T07:01:21.5523450Z /Users/runner/miniforge3/conda-bld/openmm_1651129070600/work/libraries/asmjit/asmjit/core/../core/environment.h:104:29: error: 'TARGET_OS_OSX' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_OSX]
2022-04-28T07:01:21.5524930Z #elif defined(__APPLE__) && TARGET_OS_OSX
```
I'm not sure why the preprocessor isn't working on it

**Comment by mikemhenry** [comment]
I'm really not sure what is going on here, it looks like `TargetConditionals.h` should be included on `__APPLE__` 

```
#if defined(__APPLE__)
  #include <TargetConditionals.h>
#endif
```

Is it possible that on M1 `__APPLE__` is not defined, so then `elif defined(__APPLE__) && TARGET_OS_OSX` short circuts and we don't get the `TARGET_OS_OSX` undefined error? But on intel apple, we pull in `TargetConditionals.h` but it doesn't actually define `TARGET_OS_OSX`?

**Comment by peastman** [comment]
When compiling locally on a Mac, I tried adding this code:

```c++
#include <TargetConditionals.h>
...
cout << "__APPLE__=" << __APPLE__ << endl;
cout << "TARGET_OS_OSX=" << TARGET_OS_OSX << endl;
```

I tried both an Intel Mac and an M1 Pro.  It compiles and prints the same output on both:

```
__APPLE__=1
TARGET_OS_OSX=1
```

I also verified that if I omit the `#include`, `__APPLE__` is still defined but `TARGET_OS_OSX` is not.

**Comment by peastman** [comment]
Is it possible conda-forge is shipping their own version of TargetConditionals.h rather than using the one built into the OS?  That's just the sort of thing they would do.

**Comment by peastman** [comment]
If CondaForge were installing its own copy of that file, where would I find it?  I notice the recipe includes the lines

https://github.com/conda-forge/openmm-feedstock/blob/d68725f149ed2b6cfdf89f3e197ba5d7f99f954f/.ci_support/osx_64_numpy1.21opencl_implkhronospython3.10.____cpython.yaml#L19-L20

which looks as if it were naming a machine image or something similar.  But if so, I can't figure out where it comes from.  The `macos_machine` option is never mentioned anywhere in the CondaForge documentation.

**Comment by mikemhenry** [comment]
@peastman I'm not sure, this could also be in the hands of however Microsoft handles their OSX VMs... I'm going to try seeing if any other packages using these same macros have some work around for conda-forge

**Comment by mikemhenry** [comment]
Could also be an xcode version thing, still investigating

**Comment by isuruf** [comment]
`TARGET_OS_OSX` is not defined by the macOS SDK that we are using by default. You can increase the macOS SDK version (look at the conda-forge docs) or just define `-DTARGET_OS_OSX=1` in CXXFLAGS.
Note that increasing the macOS SDK might make the package not compatible with an older version of macOS if the build system is doing function existence checks. If that's the case, then you need to increase the deployment target too. (see docs)

**Comment by peastman** [comment]
Thanks!

@mikemhenry the relevant documentation is at https://conda-forge.org/docs/maintainer/knowledge_base.html in the section labeled, "Requiring newer macOS SDKs."  I don't know what version it was added in, so let's start by trying something fairly old and work up.

**Comment by mikemhenry** [comment]
@peastman sounds good, do you think that's better than just passing `-DTARGET_OS_OSX=1` if we are doing an OSX build?

**Comment by peastman** [comment]
I think it's safer.

**Comment by peastman** [comment]
For what it's worth, the copyright date at the top of TargetConditionals.h is 2014.  Assuming that's correct, that implies it was last updated in either 10.10 or 10.11.

**Comment by mikemhenry** [comment]
I'll keep trying until it works, but it is odd (at least to me) and the osx arm builds are fine, just the intel ones that seem to be missing this macro

**Comment by isuruf** [comment]
It was introduced in 10.12. (osx-arm64 builds use 11.0 since support for osx-arm64 was added in 11.0)

**Comment by mikemhenry** [comment]
> osx-arm64 builds use 11.0 since support for osx-arm64 was added in 11.0
This is great to know, thanks!

**Comment by isuruf** [comment]
@mikemhenry, after each change you need a rerendering.

**Comment by mikemhenry** [comment]
@isuruf ha, that it explains it!!

**Comment by mikemhenry** [comment]
`osx osx_64_numpy1.19opencl_implapplepython3.8.____cpython failed` failed with an http error https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=507537&view=logs&j=a8dee1cf-d17f-5cb0-b53f-4a93dfdbfb0c&t=929f6101-935e-5679-3be5-15b073490bac&l=396 which I can reproduce locally, I'll bump CI to give it another chance but I think things are fixed now!

**Comment by mikemhenry** [comment]
@peastman as long as we don't need windows support, I think this is good to go! I'm going to build with the latest commit, then manually test the Linux package, then merge? Does that sound okay?

**Comment by peastman** [comment]
Sounds good!

**Comment by mikemhenry** [comment]
All of the tests passed locally for me with cuda 11 build of [linux-64/openmm-7.7.0dev0-py310h11b7549_0.tar.bz2](https://anaconda.org/mmh/openmm/7.7.0dev0/download/linux-64/openmm-7.7.0dev0-py310h11b7549_0.tar.bz2). So I will merge this and announce it on slack, after I get feedback I'll update the release doc you mentioned at the top of the PR.

**Pull request merged**
