### PR TITLE
Fix misreported git revision in version.py

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

Addresses https://github.com/openmm/openmm/issues/2905#issuecomment-737414824

### CODE REVIEW

**Comment by peastman** [comment]
This looks kind of fishy to me.  It guarantees that OpenMM will *report* whatever revision you specified, but doesn't guarantee it was *actually* built with that revision.  Is there a reason not to specify it like I suggested at https://github.com/openmm/openmm/issues/2905#issuecomment-737434923?

**Comment by jaimergp** [comment]
It is guaranteed because we are [pulling from that revision's URL](https://github.com/jaimergp-feedstocks/openmm-feedstock/blob/fix-revision/recipe/meta.yaml#L16). 

`staged-recipes` [does not mention `git_url`](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L13-L24) and members from core have [expressed that personal preference](https://gitter.im/conda-forge/conda-forge.github.io?at=5fc7e32432153f0d4441268a) too.

**Comment by peastman** [comment]
> staged-recipes does not mention git_url

See the documentation at https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#source-section.

> members from core have expressed that personal preference too.

One person suggested preferring a tarball over a git revision, but then added, "Note that 'my list' is not our policy."  If specifying by `git_rev` avoids needing to manually patch version.py, I think that's a good reason to prefer it in this case.  Can we try it?

**Comment by jaimergp** [comment]
Let's give it a try, yep.

The more I patched the patch the less comfortable I felt with the workaround 😬

**Comment by jaimergp** [comment]
@peastman tests fail because `AssertionError: 7.5!=7.5.0`.

Should I...

A) Uncomment this test
B) Test only major.minor (no .patch)
C) Change the version string in the recipe
D) Submit a PR to openmm so it reports 7.5.0

?

**Comment by peastman** [comment]
How about making the test tolerate either one?  Change `assert v == '{{ version }}'` to `assert v == '{{ version }}' or v+'.0' == '{{ version }}'`.

**Comment by jaimergp** [comment]
Ok, let's see how this works now!

**Pull request merged**
