### PR TITLE
pin scipy to < 1.14, see https://github.com/openmm/openmm/issues/4601

### PR DESCRIPTION
**Pull request by mikemhenry**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mikemhenry** [comment]
@conda-forge-admin, please rerender

**Comment by mikemhenry** [comment]
Not sure what is going on with the failures, they fail to import openmm, 

`ModuleNotFoundError: No module named 'openmm'`

In the build log, this also shows up:

```
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/openmm_1724181143600/work/build/python/setup.py", line 276, in <module>
    main()
  File "/home/conda/feedstock_root/build_artifacts/openmm_1724181143600/work/build/python/setup.py", line 273, in main
    setup(**setupKeywords)
  File "/home/conda/feedstock_root/build_artifacts/openmm_1724181143600/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/pypy3.9/site-packages/setuptools/__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
  File "/home/conda/feedstock_root/build_artifacts/openmm_1724181143600/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/pypy3.9/site-packages/setuptools/_distutils/core.py", line 184, in setup
    return run_commands(dist)
  File "/home/conda/feedstock_root/build_artifacts/openmm_1724181143600/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/pypy3.9/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
    dist.run_commands()
  File "/home/conda/feedstock_root/build_artifacts/openmm_1724181143600/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/pypy3.9/site-packages/setuptools/_distutils/dist.py", line 964, in run_commands
    self.run_command(cmd)
  File "/home/conda/feedstock_root/build_artifacts/openmm_1724181143600/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/pypy3.9/site-packages/setuptools/dist.py", line 945, in run_command
    super().run_command(command)
  File "/home/conda/feedstock_root/build_artifacts/openmm_1724181143600/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/pypy3.9/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
    cmd_obj.run()
  File "/home/conda/feedstock_root/build_artifacts/openmm_1724181143600/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/pypy3.9/site-packages/setuptools/command/install.py", line 86, in run
    return super().run()
  File "/home/conda/feedstock_root/build_artifacts/openmm_1724181143600/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/pypy3.9/site-packages/setuptools/_distutils/command/install.py", line 694, in run
    self.run_command('build')
  File "/home/conda/feedstock_root/build_artifacts/openmm_1724181143600/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/pypy3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/home/conda/feedstock_root/build_artifacts/openmm_1724181143600/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/pypy3.9/site-packages/setuptools/dist.py", line 945, in run_command
    super().run_command(command)
  File "/home/conda/feedstock_root/build_artifacts/openmm_1724181143600/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/pypy3.9/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
    cmd_obj.run()
  File "/home/conda/feedstock_root/build_artifacts/openmm_1724181143600/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/pypy3.9/site-packages/setuptools/_distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/conda/feedstock_root/build_artifacts/openmm_1724181143600/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/pypy3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/home/conda/feedstock_root/build_artifacts/openmm_1724181143600/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/pypy3.9/site-packages/setuptools/dist.py", line 945, in run_command
    super().run_command(command)
  File "/home/conda/feedstock_root/build_artifacts/openmm_1724181143600/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/pypy3.9/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
    cmd_obj.run()
  File "/home/conda/feedstock_root/build_artifacts/openmm_1724181143600/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/pypy3.9/site-packages/setuptools/command/build_ext.py", line 93, in run
    _build_ext.run(self)
  File "/home/conda/feedstock_root/build_artifacts/openmm_1724181143600/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/pypy3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
    self.build_extensions()
  File "/home/conda/feedstock_root/build_artifacts/openmm_1724181143600/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/pypy3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 476, in build_extensions
    self._build_extensions_serial()
  File "/home/conda/feedstock_root/build_artifacts/openmm_1724181143600/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/pypy3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 502, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/conda/feedstock_root/build_artifacts/openmm_1724181143600/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/pypy3.9/site-packages/setuptools/command/build_ext.py", line 254, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/conda/feedstock_root/build_artifacts/openmm_1724181143600/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/pypy3.9/site-packages/Cython/Distutils/build_ext.py", line 135, in build_extension
    super(build_ext, self).build_extension(ext)
  File "/home/conda/feedstock_root/build_artifacts/openmm_1724181143600/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/pypy3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 581, in build_extension
    self.compiler.link_shared_object(
  File "/home/conda/feedstock_root/build_artifacts/openmm_1724181143600/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/pypy3.9/site-packages/setuptools/_distutils/ccompiler.py", line 757, in link_shared_object
    self.link(
  File "/home/conda/feedstock_root/build_artifacts/openmm_1724181143600/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/pypy3.9/site-packages/setuptools/_distutils/unixccompiler.py", line 268, in link
    linker = (
TypeError: 'NoneType' object is not subscriptable (key slice(None, None, None))
```

But does not show up in the passing builds

**Comment by peastman** [comment]
It's not a very helpful error message.  My best guess is that one of the entries in `setupKeywords` at line 273 of setup.py is None, or something else invalid.  Can you patch it to print out the value?

**Comment by peastman** [comment]
I just got the same error from CI at https://github.com/openmm/openmm/pull/4622, but only for the Pypy build.

**Comment by peastman** [comment]
The inputs to `setup()` look fine.  I think this is the line in unixcompiler.py that's throwing the exception.

```python
linker = (self.linker_exe if building_exe else self.linker_so)[:]
```

This looks like something in the compiler stack has changed recently and broken.

**Comment by mikemhenry** [comment]
Sweet looks like it worked! any objects to merging @peastman ? after it gets merged in I'll make a repometadata patch to update the older builds with this pin.

**Comment by peastman** [comment]
Looks good!

**Pull request merged**
