### PR TITLE
Release candidate for 8.0

### PR DESCRIPTION
**Pull request by peastman**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

### CODE REVIEW

**Comment by peastman** [comment]
@conda-forge-admin, please rerender

**Comment by peastman** [comment]
What do I need to change to get it to build packages for Python 3.11?

**Comment by mikemhenry** [comment]
I manually added the python 3.11 migration file, lets see if it works :crossed_fingers:

**Comment by peastman** [comment]
It looks like it's building them!

**Comment by peastman** [comment]
Shouldn't the re-render have added those files automatically?

**Comment by mikemhenry** [comment]
So this bot pr https://github.com/conda-forge/openmm-feedstock/pull/93 adds the migration file + re-renders which then makes the python 3.11 builds show up. But since we didn't merge that PR in (and it targets a different branch anyway) I manually copied the migration file into this branch, then re-rendered it.

**Comment by peastman** [comment]
Looks good!  Let's merge and see what happens.

**Comment by mikemhenry** [comment]
I'm keeping an eye on it here: https://github.com/conda-forge/openmm-feedstock/commits/rc
Once that is done, I'll get working on the other packages

**Comment by peastman** [comment]
The builds are failing.  I'm getting a whole bunch of emails like this:

---

Hi [@conda-forge/openmm](https://github.com/orgs/conda-forge/teams/openmm)! This is the friendly automated conda-forge-webservice!

It appears that one or more of your feedstock's outputs did not copy from the
staging channel (cf-staging) to the production channel (conda-forge). :(

This failure can happen for a lot of reasons, including an outdated feedstock
token. Below we have put some information about the failure to help you debug it.

Rerendering the feedstock will usually fix these problems.

If you have any issues or questions, you can find us on gitter in the
community [chat room](https://gitter.im/conda-forge/conda-forge.github.io) or you can bump us right here.

error messages:

    invalid feedstock token

**Comment by mikemhenry** [comment]
I'll bump the CI, sometimes this happens. If it keeps happening I will raise it up to the conda-forge people 

@hmacdope The plan is to get the openmm 8 rc out this week, so first we will get this build out, then we will re-build a few pacakges that depend on it. I'm not sure if you have seen this error before, but sometimes when merging in a PR, the CI fails and the packages don't end up on conda-forge, so you have to watch the commit to the branch via a link like this: https://github.com/conda-forge/openmm-feedstock/commits/rc

**Comment by mikemhenry** [comment]
Looking at the CI, `binstar_client.errors.Conflict: ('file linux-64/openmm-8.0.0rc1-py311hd9dba1d_0.conda already exists or being uploaded for package openmm version 8.0.0rc1. if your previous upload failed, please wait 2 minutes before trying again', 409)` and here: https://anaconda.org/conda-forge/openmm/files?channel=openmm_rc I think the issue is we need to bump to rc2. I will make a PR for this.

**Comment by mikemhenry** [comment]
PR here: https://github.com/conda-forge/openmm-feedstock/pull/97

**Comment by jakirkham** [comment]
The failure is due to the token needing a reset. Please see PR ( https://github.com/conda-forge/admin-requests/pull/614 )

**Pull request merged**
