### PR TITLE
Build 7.6.0 beta

### PR DESCRIPTION
**Pull request by peastman**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

### CODE REVIEW

**Comment by peastman** [comment]
@conda-forge-admin, please rerender

**Comment by jchodera** [comment]
Shouldn't we collect the release notes [here](https://github.com/openmm/openmm/releases/tag/7.6.0beta) first?

**Comment by jchodera** [comment]
Once this is built and pushed, will it go to `main`, or another channel? The [version ordering](https://conda.io/projects/conda/en/latest/user-guide/concepts/pkg-specs.html?highlight=versioning#predictable-version-ordering) suggests that this would become the default package from `conda install -c conda-forge openmm` once pushed to `main`.

**Comment by peastman** [comment]
> Shouldn't we collect the release notes here first?

I'll put together the release notes before it's released.  Right now I'm just trying to build.

> Once this is built and pushed, will it go to main, or another channel?

It will go to the `openmm_rc` label.  See the documentation at https://github.com/openmm/openmm/blob/master/devtools/CONDA_FORGE_RELEASES.md.

**Comment by isuruf** [comment]
@jaimergp, you said that for 7.6.0, we will switch the default `opencl_impl` to `khronos` given that there'll be enough testing. Can we do that switch?

**Comment by jchodera** [comment]
Also worth considering whether we can add the variants requested in #57 so we can update the linux Folding@home core for the [COVID Moonshot](http://postera.ai/covid). 

(@isuruf: My apologies for the delay in responding to you there---we still owe you a detailed summary of the issues that led us to this conclusion! Our software scientist @dotsdl will tackle this soon! Everyone has been bandwidth-limited the last couple of weeks.)

**Comment by jaimergp** [comment]
> @jaimergp, you said that for 7.6.0, we will switch the default `opencl_impl` to `khronos` given that there'll be enough testing. Can we do that switch?

Yes, we should remove these builds. AFAIK we didn't have any reports of weird behaviours around this issue. Can you confirm @peastman?

**Comment by peastman** [comment]
We were getting a single test failing on the Linux Pypy build, which we've never seen fail anywhere else.  I suspect this is because it's using pocl to run the tests, which of course we don't support.  For the moment I just disabled running the full test suite on that build.

Since this is just a beta, I'm going to go ahead and merge it.  We may want to look into that further though.  Also, if we want to make changes to the set of variants, we need to decide that before we build the release candidate, which will be in about a month.  Let's discuss that under #57.  @jchodera or @dotsdl can you post more details there about what the issues are?

**Comment by peastman** [comment]
Never mind, I was confused!  I was looking at the main branch, which was showing the results of the last PR you merged.  The `rc` branch shows everything passing.

**Pull request merged**
