### PR TITLE
Add additional license files

### PR DESCRIPTION
**Pull request by jchodera**
Addresses #9 (accidentally omitted license files).

This PR adds the LGPL and GPL license text that applies to some components of the CUDA and OpenCL platforms.

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
You need to package for example, https://github.com/openmm/openmm/blob/ecae836ce9ce279ed99e8297fdb0c8b342f144ad/libraries/lbfgs/include/lbfgs.h#L4-L25

**Comment by jchodera** [comment]
@isuruf: Another good catch.

I think that could just be integrated into https://github.com/openmm/openmm/blob/master/docs-source/licenses/Licenses.txt, since the rest of the licenses are reproduced there.

I'll create an OpenMM issue to rectify this.

**Comment by isuruf** [comment]
Btw, have a look at https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests

**Comment by jchodera** [comment]
Whoops, sorry about this---I had misread the preferred workflow! I'll open a PR from a fork.

**Pull request closed without merging**
