### PR TITLE
bump rc number

### PR DESCRIPTION
**Pull request by mikemhenry**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mikemhenry** [comment]
@peastman hopefully this passes, then we can merge it in

**Comment by peastman** [comment]
One failure so far, but it looks like it's a timeout so probably just a random error.

**Comment by peastman** [comment]
Everything else passed.  I think it's ok to merge.

**Comment by jakirkham** [comment]
If this is only being done because of the upload issue, would hold off on this. What is needed is a token reset. Please see PR ( https://github.com/conda-forge/admin-requests/pull/614 ). Once done CI only needs to be restarted (no other changes)

**Comment by mikemhenry** [comment]
Looking here: https://github.com/conda-forge/openmm-feedstock/commits/rc 
it looks like everything worked except one build:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=639576&view=logs&j=517fe804-fa30-5dc2-1413-330699242c05&t=c10fa5f2-fdf6-5338-3bdb-c4bea7c23412&l=4682

which looks like a duplicate file problem? @jakirkham does that mean that things are actually okay since that build exists? I just want to make sure we are not missing a build from our matrix

**Comment by mikemhenry** [comment]
It does look like the files landed: https://anaconda.org/conda-forge/openmm/files?channel=openmm_rc

**Comment by jakirkham** [comment]
Yeah think this is resolved

**Pull request closed without merging**
