### PR TITLE
Build 8.2 beta

### PR DESCRIPTION
**Pull request by peastman**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

### CODE REVIEW

**Comment by peastman** [comment]
@conda-forge-admin, please rerender

**Comment by peastman** [comment]
@mikemhenry can you review?  All the builds so far are passing.

**Review by mikemhenry — CHANGES_REQUESTED** [review]
We need to target the `rc` branch instead of main, other than that it looks good!

**Comment by mikemhenry** [comment]
It looks like I have the power to do that, I will give it a go

**Comment by mikemhenry** [comment]
@conda-forge-admin, please rerender

**Comment by mikemhenry** [comment]
@conda-forge-admin, please rerender

**Comment by mikemhenry** [comment]
Can you double check that these look correct @peastman 
```
recipe/conda_build_config.yaml
recipe/meta.yaml
```

I think we can drop the scipy pin if this beta includes the fix for that issue

**Comment by peastman** [comment]
> We need to target the rc branch instead of main, other than that it looks good!

Oops, thanks for catching that!

> I think we can drop the scipy pin if this beta includes the fix for that issue

Good point.  I just removed it.

**Comment by mikemhenry** [comment]
I think we lost a rendering somewhere--I re-rendered it locally, hopefully this fixes the build

**Comment by mikemhenry** [comment]
seeing this weird thing again:
```
2024-09-26T16:48:23.0615574Z     self.link(
2024-09-26T16:48:23.0616392Z   File "/home/conda/feedstock_root/build_artifacts/openmm_1727368614993/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/pypy3.9/site-packages/setuptools/_distutils/unixccompiler.py", line 268, in link
2024-09-26T16:48:23.0616885Z     linker = (
2024-09-26T16:48:23.0617231Z TypeError: 'NoneType' object is not subscriptable (key slice(None, None, None))
2024-09-26T16:48:23.0769746Z [100%] Built target PythonInstall
```

**Comment by peastman** [comment]
That's the same error we got in https://github.com/conda-forge/openmm-feedstock/pull/139.  In that case, rerendering fixed it.

**Comment by peastman** [comment]
@conda-forge-admin, please rerender

**Comment by peastman** [comment]
The tests passed this time.  It's ready to merge as far as I'm concerned.

**Comment by mikemhenry** [comment]
```
MNT: Re-rendered with conda-build 24.9.0, conda-smithy 3.40.1, and conda-forge-pinning 2024.09.26.07.35.45
MNT: Re-rendered with conda-build 24.3.0, conda-smithy 3.40.1, and conda-forge-pinning 2024.09.26.07.35.45
```

weird, I don't understand how re-rendering it did anything since the versions are the same... but yes this looks good! I will let people in the OpenMM ecosystem know there is a beta to test! :rocket:

**Comment by mikemhenry** [comment]
I will keep an eye on the CI to make sure the builds get uploaded

**Comment by peastman** [comment]
Hold off on making any announcements.  The next step is to build the HIP package.  Once everything is successfully built, then we can announce it.

**Comment by mikemhenry** [comment]
grumble, one build failed `win win_64_cuda_compilernvcccuda_compiler_version11.8numpy1.26python3.12.____cpython` since this is just the rc, I am inclined to not worry about it unless someone really needs that build for testing. The failure was just in uploading the package.

**Pull request merged**
