### PR TITLE
(DNM) Test nvidia's cuda packages for 11.6

### PR DESCRIPTION
**Pull request by jaimergp**
MNT: Re-rendered with conda-build 3.21.4, conda-smithy 3.16.2, and conda-forge-pinning 2022.02.03.19.17.39

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Do not merge. Just testing things. Sorry about the noise!

### CODE REVIEW

**Comment by jaimergp** [comment]
I see that the `cuda-nvcc` packages are now platform-suffixed so they should be compatible with the `compiler` jinja function. However, I couldn't test that out because rerendering fails and I don't have more time. I looked at the metadata and they don't have host or run exports though. Maybe the underlying packages do? 

So for now I am still hardcoding the nvcc name. That said, CUDA was not detected by CMake now. Feel free to poke around here @jakirkham

**Comment by jaimergp** [comment]
Windows does work though!

**Comment by jakirkham** [comment]
> So for now I am still hardcoding the nvcc name. That said, CUDA was not detected by CMake now. Feel free to poke around here

Our CMake packages are out-of-date, there is a build failure with the latest one on Windows ( https://github.com/conda-forge/cmake-feedstock/pull/155 ). Unfortunately I've not been able to figure this out.

**Comment by jakirkham** [comment]
Now that PR ( https://github.com/conda-forge/openmm-feedstock/pull/108 ) is in, should we close this?

Thanks again Jaime for doing this exploratory work to help guide the effort! 🙏

**Pull request closed without merging**
