### PR TITLE
Release 7.6.0

### PR DESCRIPTION
**Pull request by peastman**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

### CODE REVIEW

**Comment by jchodera** [comment]
Tagging in critical issue https://github.com/ParmEd/ParmEd/issues/1185, which may require we roll back this release and try again once we've solved the ParmEd dependency issue.

**Comment by jchodera** [comment]
@jaimergp : Apologies for calling for help, but it looks like the conda package for OpenMM 7.6 breaks anything in the ecosystem that uses ParmEd + OpenMM: see https://github.com/ParmEd/ParmEd/issues/1185

Is there a way we can constrain the openmm 7.6.0 package to _not_ be used if parmed is required, as in [this suggestion](https://github.com/ParmEd/ParmEd/issues/1185#issuecomment-907501593), but not bring in parmed as a dependency? If so, we can rapidly release a new build iteration and anything using parmed will still use older OpenMM releases until we can address https://github.com/ParmEd/ParmEd/issues/1185 via a ParmEd release.

Otherwise, we may need to urgently un-deploy the openmm 7.6.0 packages.

**Comment by peastman** [comment]
Don't worry about it.  The new ParmEd release is in process at https://github.com/conda-forge/parmed-feedstock/pull/15.  It should be out shortly.

**Comment by peastman** [comment]
@jaimergp any idea what I can do about the one broken build mentioned above?

**Comment by jaimergp** [comment]
A repodata patch.

Look here: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock

**Comment by peastman** [comment]
Another question for @jaimergp while you're at it.  I just created a new Github release of PDBFixer to go with the new OpenMM.  Do I need to update the feedstock to build packages for it, or will conda-forge do that automatically?

**Comment by jaimergp** [comment]
If you cut a new GH release (not just a tag), the bot should pick it. If for some reason it doesn't, you can always create it manually.

**Comment by jchodera** [comment]
@peastman : Let's give it to the end of the day, but we have to figure out how to roll back the 7.6 release if we can't get https://github.com/ParmEd/ParmEd/issues/1185 resolved by the end of the day. We have a bunch of downstream projects where nobody can do anything because we broke the OpenMM/ParmEd dependent ecosystem.

I realize this is not necessarily OpenMM's fault, but until the ParmEd replacement project (which OpenFF has at least 1 person working full time now) is ready, we're stuck in a situation where this has broken everything.

The [`run_constrained`](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#run-constrained) suggestion from @mattwthompson is likely what we will need to implement in the conda-recipe to work around the ParmEd issues.

**Comment by peastman** [comment]
> We have a bunch of downstream projects where nobody can do anything because we broke the OpenMM/ParmEd dependent ecosystem.

Just `conda install openmm=7.5.1`.  Rolling back a release would cause disruption to all the other projects in the ecosystem that depend on OpenMM.

**Comment by jchodera** [comment]
> Just conda install openmm=7.5.1. 

In order for this to work, we would have to change every conda recipe, override every continuous integration pipeline, and modify every dependency to specify this. This would require an impossible amount of effort.

> Rolling back a release would cause disruption to all the other projects in the ecosystem that depend on OpenMM.

Exactly what will it disrupt? Considering it didn't exist three days ago, there is essentially nothing that would be disrupted.

**Comment by mattwthompson** [comment]
In the past I've used https://github.com/conda-forge/admin-requests to get a `broken` label added to one of my packages, although that was not with the intent of removing it, so that might not be the best approach in this case.

Pinning to 7.5.x for a period of time can work for some people (including me -  I'd only have to do that in one location and it would naturally percolate out everywhere in the OpenFF stack) but it's not a viable general solution IMHO

**Pull request merged**
