### PR TITLE
Add ppc 10.2

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jaimergp** [comment]
Some fixes needed in the Docker image. Pending https://github.com/conda-forge/docker-images/pull/181

**Comment by jaimergp** [comment]
@peastman 

PPC64LE fails with OpenCL (both `pocl` and `oclgrind`). It gives `nan` forces in the `simtk.testInstallation` routines.

[More details](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=318960&view=logs&j=ed770ae4-53fd-5da6-198f-2ced939e4aba&t=63a40b86-1593-5cf6-c9b4-b3934efbfee3&l=8422).

**Comment by peastman** [comment]
No idea what's causing it.  We don't support either of those OpenCL implementations, and there's no information in the log beyond the fact that it produced nan.  I notice the CUDA platform also failed.  What kind of hardware is it running on?  Is it using emulation?

**Comment by jaimergp** [comment]
CUDA will not run on this CI. The OpenCL tests did pass on the other platforms, but I guess we'll have to disable for PPC and test with local artifacts.

**Comment by raimis** [comment]
Soon I'll have access to a machine with `ppc64le` CPU and V100 GPU. Would it be possible to disable the OpenCL tests so the builds finish and the packages are available to test?

**Comment by jaimergp** [comment]
Yes, definitely. Let's see if this commit works first!

**Comment by raimis** [comment]
I tried to build the package on real hardware:
```
$ uname -a
Linux login02 4.18.0-147.13.2.el8_1.ppc64le #1 SMP Wed May 13 15:23:36 UTC 2020 ppc64le ppc64le ppc64le GNU/Linux
```
```
$ nvidia-smi -L
GPU 0: Tesla V100-SXM2-16GB (UUID: GPU-285ad857-3f51-bece-1a26-111b71801e3c)
GPU 1: Tesla V100-SXM2-16GB (UUID: GPU-4e6c7741-1786-866f-ec22-8036fbc79926)
GPU 2: Tesla V100-SXM2-16GB (UUID: GPU-724c10eb-1b65-92da-a810-d0ce94e16f6c)
GPU 3: Tesla V100-SXM2-16GB (UUID: GPU-9026bf81-cece-693a-af05-f54a1e412d36)
```
Except OpenCL, it works:
```
$ python -m simtk.testInstallation

OpenMM Version: 7.5.1
Git Revision: a9cfd7fb9343e21c3dbb76e377c721328830a3ee

There are 4 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 CUDA - Successfully computed forces
4 OpenCL - Error computing forces with OpenCL platform

OpenCL platform error: Error compiling kernel: 

Median difference in forces between platforms:

Reference vs. CPU: 6.29803e-06
Reference vs. CUDA: 6.72703e-06
CPU vs. CUDA: 6.59765e-07

All differences are within tolerance.
```

So, it seems the CI fails just due to a missing GPU.

**Comment by jaimergp** [comment]
Excellent! I am sorry I haven't got back to this yet. Between vacation and onboarding I still have some open issues to track down. This is on my list though. I'll get to it shortly!

**Comment by peastman** [comment]
I wonder why OpenCL failed to compile a kernel?  Could you try running a few of the test cases?  For example,

```
./TestOpenCLHarmonicBondForce
./TestOpenCLNonbondedForce
```

Does it give any more information?

**Comment by raimis** [comment]
Just non-descriptive error messages:
```
$ ./TestOpenCLHarmonicBondForce
exception: Error compiling kernel:
```
```
$ ./TestOpenCLNonbondedForce
exception: Error compiling kernel: 
```

**Comment by peastman** [comment]
Very strange.  And yet OpenCL did work on CI.  I don't know whether it's worth spending a lot of time to investigate, since the number of people using NVIDIA OpenCL on PPC is likely to be close to zero.

**Comment by jaimergp** [comment]
Should we disable OpenCL on PPC then?

**Comment by peastman** [comment]
I would hesitate to do that without more information.  We don't know why it's failing on that one particular computer.  It might have nothing to do with the fact that it's PPC.  We also have no reason to think the same error would happen with other OpenCL implementations.

**Comment by jchodera** [comment]
@peastman: Didn't we get you access to a `ppc64le` machine at some point?

**Comment by raimis** [comment]
> Very strange. And yet OpenCL did work on CI. I don't know whether it's worth spending a lot of time to investigate, since the number of people using NVIDIA OpenCL on PPC is likely to be close to zero.

The CI machine doesn't have a GPU, so OpenCL tries to run on a CPU and succeeds. My machine has GPUs, so OpenCL tries to use them and fails, I guess. Anyway, OpenCL is irrelevant in this case.

So far, all the PPC machines I have seen exclusively have V100 GPUs. So, if we make a package with CUDA 10.2, it will cover most (if not all) use cases.

**Comment by peastman** [comment]
> @peastman: Didn't we get you access to a ppc64le machine at some point?

See https://github.com/conda-forge/openmm-feedstock/pull/55#issuecomment-853243580.

**Comment by jaimergp** [comment]
Ok, this is ready to go if everybody agrees.

**Review by peastman — APPROVED** [review]

**Comment by raimis** [comment]
Thanks @jaimergp!

**Pull request merged**
