### PR TITLE
WIP · ppc64le support

### LINKED ISSUE #8: PowerPC builds
`ppc64le` are technically possible, but in reality there are some barriers. I will collect relevant issues and PRs here.

# All

- [ ] `doxygen` has no `ppc64le` build yet. I am submitting a [PR here](https://github.com/conda-forge/doxygen-feedstock/pull/11), but we will also need to ask to build version 1.8.14, since .16 fails with current `openmm`.

# CUDA 

- [ ] The overall GPU support in `conda-forge` assumes a one-to-one relationship between CUDA versions and Docker images because it only considers `x64` architectures. This should be addressed in `conda-smithy` and `nvcc`. [Tracking issue](https://github.com/conda-forge/nvcc-feedstock/issues/21).
- [ ] Create CUDA Docker images for `ppc64le`. Problem: Nvidia only provides CentOS 7, no CentOS 6.
- [ ] Anaconda only provides `cudatoolkit` v9.0 for `ppc64le`.

# OpenCL

- [ ] `ocl-icd` could be used to trigger the compilation of the OpenCL parts, but it doesn't have a `ppc64le` build yet. A PR should be submitted

We could get an OpenCL + CPU build with relatively low effort if we fix `doxygen` and `ocl-icd`. Would this be enough?

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
* [X] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged) -- building new architectures only
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

This will resolve #8 

## Blocking issues

- [x] `ocl-icd-system` is not yet ready for `ppc64le` and `aarch64`. [PR here](https://github.com/conda-forge/ocl-icd-system-feedstock/pull/1).
- [x] `doxygen 1.8.14` is not available for `ppc64le` and `aarch64`. There is `1.8.16`, but we need `1.8.14` for OpenMM. Submitted a PR [here](https://github.com/conda-forge/doxygen-feedstock/pull/12).
- [x] `lxml` cannot be found in `aarch64`. `ppc64le` is indeed available for `ppc64le`, but only through `defaults`. Submitted PR to `conda-forge` [here](https://github.com/conda-forge/lxml-feedstock/pull/42).

Once dependencies are solved, keep an eye on issues like [this one](https://github.com/jaimergp/staged-recipes/issues/1#issuecomment-524210286):

```
import: 'simtk'
import: 'simtk.openmm'
+ python -m simtk.testInstallation
/home/conda/feedstock_root/build_artifacts/openmm-cpu_1566489851175/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.6/site-packages/numpy/core/getlimits.py:53: RuntimeWarning: divide by zero encountered in log10
  self.precision = int(-log10(self.eps))
/home/conda/feedstock_root/build_artifacts/openmm-cpu_1566489851175/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.6/site-packages/numpy/core/getlimits.py:53: RuntimeWarning: overflow encountered in log10
  self.precision = int(-log10(self.eps))

OpenMM Version: 7.4
Git Revision: Unknown

There are 2 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces

Median difference in forces between platforms:

Problem with OpenMM installation encountered. OpenMM will not work until the problem has been fixed.


Error message: 0.0 cannot be raised to a negative power
```

### CODE REVIEW

**Comment by jaimergp** [comment]
@conda-forge-admin, please rerender

**Comment by jaimergp** [comment]
All needed dependencies are now available! However, builds for PowerPC and ARM are failing for different reasons (although apparently related to the same thing?).

`ppc64le` fails [here](https://travis-ci.com/conda-forge/openmm-feedstock/jobs/263721715#L2680) (this error appears several times). We might be able to fix it by adding the suggested flag (`-DNO_WARN_X86_INTRINSICS`).

```
/home/conda/feedstock_root/build_artifacts/openmm_1575605736402/work/platforms/opencl/src/OpenCLArray.cpp:27:
/home/conda/feedstock_root/build_artifacts/openmm_1575605736402/_build_env/lib/gcc/powerpc64le-conda_cos7-linux-gnu/8.2.0/include/emmintrin.h:56:2: error: #error "Please read comment above.  Use -DNO_WARN_X86_INTRINSICS to disable this error."
 #error "Please read comment above.  Use -DNO_WARN_X86_INTRINSICS to disable this error."
  ^~~~~
```


`aarch64` fails [here](https://cloud.drone.io/conda-forge/openmm-feedstock/5/1/2) (line 2599; this error appears several times too):

```
/drone/src/build_artifacts/openmm_1575605706819/work/platforms/cpu/src/CpuPlatform.cpp:34:
--
2599 | /drone/src/build_artifacts/openmm_1575605706819/work/openmmapi/include/openmm/internal/vectorize_sse.h:35:10: fatal error: smmintrin.h: No such file or directory
2600 | #include <smmintrin.h>
2601 | ^~~~~~~~~~~~~
2602 | compilation terminated.
```

Is there anything special about intrinsics in PowerPC/ARM when it comes to OpenMM, @peastman? Why does the compiler does not include `smmintrin.h` and `emmintrin.h` in ARM, @isuruf?

**Comment by jaimergp** [comment]
# PowerPC

I got `ppc64le` to build by adding the `DNO_WARN_X86_INTRINSICS` flag! I am not seeing the precision issues reported in previous attempts, but the Reference vs CPU diffs are too large:

```
$ python -m simtk.testInstallation
OpenMM Version: 7.4.1
Git Revision: 7ad4af319497da5ce4b3040e8b03d5860d4082a2
There are 2 Platforms available:
1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
Median difference in forces between platforms:
Reference vs. CPU: 0.194358  *** LARGE DIFFERENCE **
```

Is there any other workaround for this issue?

Notice that OpenCL is built too, but we cannot test it because `pocl` is not available for these architectures.

# ARM

These don't work yet.

For some reason, the compiler tries to use the x86 intrinsics, although I can see mentions to Neon instructions in the CMake configurations in OpenMM. Is there any extra flag I need to define to disable these, @peastman?

**Comment by peastman** [comment]
We have different versions of the vectorization code for x86, PPC, and ARM.  It's supposed to automatically pick the correct one based on the architecture you're compiling for, but it looks like something is going wrong with that.  Here's the section of the CMake script that does it: 

https://github.com/openmm/openmm/blob/2ca749a164af6023653b3044b21056a7dd2b33a6/CMakeLists.txt#L36-L49

We then include the correct header based on which of those symbols was defined:

https://github.com/openmm/openmm/blob/master/openmmapi/include/openmm/internal/vectorize.h

**Comment by jaimergp** [comment]
Thanks for the tip! I defined some variables to force the architecture detection, and that reduced the number of errors. However there are still some:

- [PPC ](https://travis-ci.org/conda-forge/openmm-feedstock/jobs/622021464?utm_medium=notification&utm_source=github_status)has the same errors, but it only comes from the OpenCL platform.
- [ARM ](https://cloud.drone.io/conda-forge/openmm-feedstock/9/2/2)seems to be related to the C wrapper? It's only one error in this case.

**Comment by peastman** [comment]
I see the problem on ARM.  It's this line: https://github.com/openmm/openmm/blob/master/libraries/vecmath/src/vecmath.cpp#L1.  It ought to be `#if defined(__ARM__)`, not `#if defined(__ANDROID__)`.

I'm a little confused about the PPC error.  cl.hpp contains these lines:

```c++
#if defined(linux) || defined(__APPLE__) || defined(__MACOSX)
#include <alloca.h>

#include <emmintrin.h>
#include <xmmintrin.h>
#endif // linux
```

That seems to assume Linux will always be x86.  But we've successfully compiled on Linux PPC before.  So what is different this time, and why did those lines not cause problems before?

**Comment by jaimergp** [comment]
Re PPC, maybe we were using a different compiler (older GCC, clang, etc) where the intrinsics can be used without the error? It's actually a warning turned error because we are not defining `NO_WARN_X86_INTRINSICS`.

**Comment by jaimergp** [comment]
I re-added `NO_WARN_X86_INTRINSICS` to fix the OpenCL errors in PPC, but the large differences in Reference vs CPU [are still there](https://travis-ci.com/conda-forge/openmm-feedstock/jobs/264826488#L7246). I thought it would be caused by the intrinsics thing, but apparently it's not.

Regarding ARM, patching `ANDROID` to `ARM` in that line allowed the compilation to continue, uncovering the same OpenCL error later in the build. In this arch, `gcc` does not provide the intrinsics headers, so we can't use `NO_WARN_X86_INTRINSICS`. I guess there is not easy patch to apply in this case, right?

There's also this other error:

```
/drone/src/build_artifacts/openmm_1575800787904/work/openmmapi/include/openmm/internal/vectorize_neon.h:35:10: fatal error: cpu-features.h: No such file or directory
```

Is that Android specific?

**Comment by peastman** [comment]
For the PPC intrinsics error, possibly we just need to upgrade to the latest version of cl.hpp.  I see it no longer imports the Intel intrinsics. https://github.com/KhronosGroup/OpenCL-CLHPP/blob/master/include/CL/cl.hpp

> Is that Android specific?

Yes, you're right.  It's being used in this code:

```c++
static bool isVec4Supported() {
    uint64_t features = android_getCpuFeatures();
    return (features & ANDROID_CPU_ARM_FEATURE_NEON) != 0;
}
```

As you can tell, Android is the only platform where we've ever compiled for ARM before.  We need to figure out how to replace that with something that isn't Android specific.

**Comment by jaimergp** [comment]
@conda-forge-admin, please rerender

**Comment by jaimergp** [comment]
Disabling ARM for now. I'll open a PR for that one once the errors mentioned above have been fixed.

**Comment by jaimergp** [comment]
Still observing large differences in forces.

**Comment by jaimergp** [comment]
Closing this one. Work will continue on #23

**Pull request closed without merging**
