### PR TITLE
Release candidate for 8.2

### PR DESCRIPTION
**Pull request by peastman**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

### CODE REVIEW

**Comment by peastman** [comment]
@conda-forge-admin, please rerender

**Comment by peastman** [comment]
@mikemhenry can you review?

**Comment by peastman** [comment]
The ARM Linux builds are failing:

```
2024-10-21T21:09:19.5155278Z [ 83%] Linking CXX shared library ../../../libOpenMMCUDA.so
2024-10-21T21:09:19.5660903Z /home/conda/feedstock_root/build_artifacts/openmm_1729544387314/_build_env/bin/../lib/gcc/aarch64-conda-linux-gnu/11.4.0/../../../../aarch64-conda-linux-gnu/bin/ld: /usr/local/cuda/lib64/libnvrtc.so: error adding symbols: file in wrong format
2024-10-21T21:09:19.5683100Z collect2: error: ld returned 1 exit status
```

**Comment by peastman** [comment]
Only the ones for CUDA 11.8 failed.  The ones for 12 and for no CUDA passed.

**Comment by peastman** [comment]
I'm at a loss for what to do about it.  The same builds worked when we built the beta a month ago.  Clearly something has changed external to this repo.  Is there a way we can just disable that particular combination of builds (CUDA 11.8 on ARM Linux)?

**Comment by mikemhenry** [comment]
> I'm at a loss for what to do about it. The same builds worked when we built the beta a month ago. Clearly something has changed external to this repo. Is there a way we can just disable that particular combination of builds (CUDA 11.8 on ARM Linux)?

Yah that will be the past of least resistance, I can do that! Seems like a waste to try and get the builds working until we need them since things might change (like dropping an older cuda version) before we get 8.2 released fully

**Comment by peastman** [comment]
I'm hoping to get 8.2 fully released next week.  The release generally follows the rc by a week, if no problems are found.  But CUDA 11.8 on ARM Linux is sufficiently obscure that if we need to skip it, I think that's ok.  CUDA 12 has been out for almost two years.

**Comment by mikemhenry** [comment]
Sounds good, see this commit: https://github.com/conda-forge/openmm-feedstock/pull/143/commits/36e8691d9834f5cf791ac31b78928472b503ae24
 it looks I removed the builds you requested!

**Comment by mikemhenry** [comment]
Confusing we are getting a new build failure on `Build linux linux_aarch64_c_compiler_version12cuda_compilercuda-nvcccuda_compiler_version12.0cxx_compiler_version12numpy1.22python3.10.____cpython failed` 

```
conda_libmamba_solver.exceptions.LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides requested sysroot_linux-aarch64 2.17**
  - nothing provides requested cuda-version 12.0**
  - nothing provides requested mesa-libgl-devel-cos7-aarch64
  - nothing provides cuda-cudart-dev_linux-aarch64 12.0.* needed by cuda-nvcc_linux-aarch64-12.0.76-h39475eb_10
  - nothing provides tzdata needed by python-3.10.0-h543edf9_1_cpython
  - nothing provides sysroot_linux-aarch64 needed by gxx_linux-aarch64-12.1.0-hf89e22a_10
  - nothing provides sysroot_linux-64 needed by gcc_linux-aarch64-12.1.0-h93c90ae_10
  - nothing provides crossenv >=1.0 needed by cross-python_linux-aarch64-3.10-13_cpython

Could not solve for environment specs
The following packages are incompatible
├─ cross-python_linux-aarch64 is not installable because there are no viable options
│  ├─ cross-python_linux-aarch64 [3.10|3.11|...|3.9] would require
│  │  └─ crossenv >=1.0 , which does not exist (perhaps a missing channel);
│  ├─ cross-python_linux-aarch64 [3.6|3.7|3.8|3.9] would require
│  │  └─ crossenv, which does not exist (perhaps a missing channel);
│  └─ cross-python_linux-aarch64 [3.10|3.11|...|3.9] would require
│     └─ crossenv >=1.1.4 , which does not exist (perhaps a missing channel);
├─ cuda-nvcc_linux-aarch64 12.0**  is not installable because it requires
│  └─ cuda-cudart-dev_linux-aarch64 12.0.* , which does not exist (perhaps a missing channel);
├─ cuda-version 12.0**  does not exist (perhaps a typo or a missing channel);
├─ gcc_linux-aarch64 12**  is not installable because it requires
│  └─ sysroot_linux-64, which does not exist (perhaps a missing channel);
├─ gxx_linux-aarch64 12**  is not installable because it requires
│  └─ sysroot_linux-aarch64, which does not exist (perhaps a missing channel);
├─ mesa-libgl-devel-cos7-aarch64 does not exist (perhaps a typo or a missing channel);
├─ python 3.10* *_cpython is not installable because it requires
│  └─ tzdata, which does not exist (perhaps a missing channel);
└─ sysroot_linux-aarch64 2.17**  does not exist (perhaps a typo or a missing channel).
```

but yesterday it worked...

**Comment by mikemhenry** [comment]
sorry false alarm:
```
An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
'https//conda.anaconda.org/conda-forge/linux-64'
```

**Comment by peastman** [comment]
All builds passed.  Shall I merge it?

**Comment by mikemhenry** [comment]
Go for it!

**Comment by peastman** [comment]
Thanks.  Next for the HIP plugin...

**Pull request merged**
