### PR TITLE
Linux builds are failing 

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
* [X] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

Azure fails with the following message for Linux (MacOS is ok):

```
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {'pin_subpackage'}
```

### CODE REVIEW

**Comment by jaimergp** [comment]
@conda-forge-admin, please rerender

**Comment by jaimergp** [comment]
I thought it could be solved with the rerender, but turns out it's not. Any ideas @isuruf, @jakirkham ? Thanks!

**Comment by jakirkham** [comment]
I'm not able to see the failure as there are no logs. Have triggered a rebuild to see if we can get them.

**Comment by jaimergp** [comment]
The rebuild did the trick, somehow. If you are curious about the errors, they are also listed in currrent `master`: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=85027&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e

I guess some of the metadata files were out of date and missing `pin_subpackage`. We can merge this if everybody agrees.

**Pull request merged**
