### PR TITLE
[Do not merge] PPC64LE / AARCH64 support

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
* [X] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

# Current status

## ARM

Reference and CPU working. OpenCL via `pocl` looks like it's working too.

## PowerPC

Previous bug with different GCC versions was solved. CUDA support is now possible too (only v10.2). Waiting on https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/725 so `smithy` can re-render the repo with support.

### CODE REVIEW

**Comment by jaimergp** [comment]
@conda-forge-admin, please rerender

**Comment by jchodera** [comment]
Wow, does this work already @jaimergp ?

**Comment by jaimergp** [comment]
> Wow, does this work already @jaimergp ?

No clue, I recall there were some precision issues in last attempt. Let's see if the new OpenMM has fixes for this.

**Comment by jaimergp** [comment]
So both ARM and PPC compile, but there are some runtime linking problems with OpenCL. This might be due to a missing dependency and I will debug that locally.

I see that the OpenMM CI does not have that problem (nor the "large difference in forces" PPC has here), so I guess there's a compiler/library situation we need to resolve anyway, OpenCL involved or not.

**Comment by isuruf** [comment]
> but there are some runtime linking problems with OpenCL.

This is a bug with the POCL conda package. I'll fix it this weekend.

**Comment by isuruf** [comment]
Fixed in https://github.com/conda-forge/pocl-feedstock/commit/cb201c259b0f393c4888bc6d1ef0f1d8eaaf8b96

**Comment by jaimergp** [comment]
Confirmed, GCC 8.5 as provided by `apt` reproduces the large differences in PowerPC too. Check [logs for attempt here](https://travis-ci.com/github/jaimergp/openmm/jobs/342939743#L7125).

@peastman Do you think this difference in behavior qualifies as a bug that must be addressed at `openmm/openmm`?

**Comment by peastman** [comment]
We definitely need to track down what's causing it.

**Comment by isuruf** [comment]
Can openmm use clang? We have clang compilers for linux too.

**Comment by jchodera** [comment]
> Can openmm use clang? We have clang compilers for linux too.

Yes! I think @peastman even prefers `clang`.

**Comment by jchodera** [comment]
We use [clang in the `omnia` recipe](https://github.com/omnia-md/conda-recipes-cuda/blob/master/openmm/build.sh#L23-L24), for example.

**Comment by isuruf** [comment]
I restarted the builds. Looks like CPU works fine on aarch64 and POCL works fine on ppc64le and aarch64.

**Comment by jaimergp** [comment]
Currently blocking issue is discussed here: https://github.com/openmm/openmm/issues/2722

**Comment by isuruf** [comment]
Switching to clang fails with,

```
In file included from /home/conda/feedstock_root/build_artifacts/openmm_1594059750456/work/openmmapi/include/openmm/internal/vectorize.h:38:

/home/conda/feedstock_root/build_artifacts/openmm_1594059750456/work/openmmapi/include/openmm/internal/vectorize_ppc.h:286:20: error: use of overloaded operator '+' is ambiguous (with operand types 'fvec4' and '__vector float' (vector of 4 'float' values))

    fvec4 temp = r + vec_sld(r.val, r.val, 8);

                 ~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by jaimergp** [comment]
Yeah, we had tried that in #26 and arrived to the same conclusion :/

**Comment by jaimergp** [comment]
Thanks to latest changes in `master`, there's no precision issues with CPU anymore! Thank you so much @peastman and @isuruf!

**Comment by jchodera** [comment]
Huzzah! Thanks so much, everybody!

**Comment by jaimergp** [comment]
Will be superseded by #36

**Pull request closed without merging**
