### PR TITLE
Updated beta for 8.0

### PR DESCRIPTION
**Pull request by peastman**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

We finally have the OpenMM-Torch build issues resolved and can move forward with the beta.  This updates the source revision to get the latest changes.

### CODE REVIEW

**Comment by peastman** [comment]
@conda-forge-admin, please rerender

**Comment by peastman** [comment]
All of the builds for ARM Mac failed with this error:

```
2022-09-13T19:51:11.9299260Z /Users/runner/miniforge3/etc/profile.d/conda.sh: line 9:  6048 Segmentation fault: 11  "$CONDA_EXE" $_CE_M $_CE_CONDA "$@"
```

Any idea what could be causing it?

**Comment by peastman** [comment]
Possibly it's related to the fact that tests only get run on ARM?  @jaimergp it looks like you introduced that in a commit on Jan. 21, 2021.  Do you remember why?  In any case, it passed when we did the last build two months ago.

**Comment by jaimergp** [comment]
IIRC, it's due to the fact we can't run ARM64 code on the regular CI. 

We included this line

https://github.com/conda-forge/openmm-feedstock/blob/036712c3b1647d28ee2bb5d1df6c1581a6390a70/recipe/meta.yaml#L5

so the tests get included in the final package, and we could test the artifacts locally, because we couldn't be sure cross-compilation was not introducing errors in the unit tests. If you are confident the process works ok, I guess you can remove it!

**Comment by jaimergp** [comment]
It might also do [with the patching we needed for OSX tests](https://github.com/peastman/openmm-feedstock/blob/036712c3b1647d28ee2bb5d1df6c1581a6390a70/recipe/build_openmm.sh#L72-L85), which had wrong rpaths or something. The patching was needed to make tests relocatable, iirc. This way people can test the package locally with `conda build --test <tarball>`. But if that's getting in the way, go ahead and skip it.

It'd be nice to know why it's segfaulting now, though. I'd start by comparing the versions of the packages installed in the build and host environments in both commits, but up to you.

**Comment by peastman** [comment]
Let's try leaving out the tests and see what happens.  Something upstream must have changed in the last two months to cause the error to appear.

**Comment by peastman** [comment]
That seems to have worked.  Shrug?  Since this is just a beta, let's go ahead with it.  We'll see if any problems come up when users start working with it.

**Pull request merged**
