### PR TITLE
Build new dev package

### PR DESCRIPTION
**Pull request by peastman**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

This is to get the changes from https://github.com/openmm/openmm/pull/4585.  I'll be adding features to PDBFixer that require it, so I need a package for CI to use.

### CODE REVIEW

**Comment by peastman** [comment]
@conda-forge-admin, please rerender

**Comment by peastman** [comment]
A lot of builds are failing with

> failed with error: [Errno 28] No space left on device

**Comment by peastman** [comment]
I have everything else passing, but a lot of the ARM Linux builds fail with the `No space left on device` error.  @mikemhenry @jaimergp do you have any idea what we can do about it?

**Comment by jaimergp** [comment]
That's odd. The build didn't even start 🤔 You can try to free some space with these lines in `conda-forge.yml` (repo root)

```yaml
azure:
  free_disk_space: true
```

Then rerender.

See https://conda-forge.org/docs/maintainer/conda_forge_yml/#azure for details

**Comment by peastman** [comment]
@conda-forge-admin, please rerender

**Comment by peastman** [comment]
That worked, thanks!

**Pull request merged**
